name: 🚀 Renderer Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.2.0)'
        required: true
        type: string

      changelog:
        description: 'Changelog to build (e.g., 1.2.0)'
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          repository: 'innei/Torrent-Vibe-Private'
          fetch-depth: 1
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build renderer
        run: pnpm run build:production

      - name: Archive renderer dist
        run: tar -czf renderer-dist.tar.gz -C layer/renderer dist

      - name: Encrypt package
        run: |
          node scripts/encrypt-update-package.js \
          --input renderer-dist.tar.gz \
          --public-key resources/security/update_pubkey.pem \
          --private-key resources/security/update_privkey.pem \
          --version ${{ inputs.version }} \
          --output renderer-dist-encrypted.bin
      - name: Generate SHA256
        run: |
          if command -v shasum >/dev/null 2>&1; then
            shasum -a 256 renderer-dist-encrypted.bin | awk '{print $1}' > renderer-dist-encrypted.sha256
          else
            sha256sum renderer-dist-encrypted.bin | awk '{print $1}' > renderer-dist-encrypted.sha256
          fi
      - name: Upload renderer artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          generate_release_notes: false
          fail_on_unmatched_files: false
          append_body: true
          body: ${{ inputs.changelog }}
          make_latest: true
          files: |
            renderer-dist-encrypted.bin
            renderer-dist-encrypted.sha256
